# Site settings
title: GRE
email: your-email@domain.com
url: https://example.github.io
description: "This is a special web to show the benchmarking result of many indexes by GRE, our outstanding Index benchmarking method. The following pages will present the heatmap, line chart and table to you. And if you want to contribute to this benchmark method, there are also ways to upload your own index or dataset."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#f1f1f1'
  links: '#219ab3'

# Footer settings
footer: GRE

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket
    url: 
  - title: github
    url: 

# Build settings
markdown: kramdown
permalink: pretty
